language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_install:
  - chmod +x gradlew

script:
  - ./gradlew test
  - ./gradlew sonarqube -Dsonar.login=$SONAR_USER -Dsonar.password=$SONAR_PASSWORD