language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build sonarqube -Dsonar.login=$SONAR_USER -Dsonar.password=$SONAR_PASSWORD -DSF_API_KEY=$SF_API_KEY
